### PR TITLE
Include GitHub Actions docs

### PR DESCRIPTION
**Pull request by estruyf**
Added the documentation for using Dev Proxy in GitHub Actions workflow.

### CODE REVIEW

**Comment by Court72** [comment]
@estruyf - Thank you for your contribution. Someone from the content team will reach out with next steps.

**Comment by Court72** [comment]
#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Review by waldekmastykarz — APPROVED** [review]
Awesome!

**Comment by waldekmastykarz** [comment]
#sign-off

**Comment by ShannonLeavitt** [comment]
@waldekmastykarz

PRMerger will accept sign-off from the listed author only. However, if you are a Microsoft employee authorized to update this content, you can send a request to techdocprs@microsoft.com for this PR to be merged. Please include your role and an explanation of why the PR should be merged without approval from the listed author.

**Comment by estruyf** [comment]
#sign-off

**Comment by Court72** [comment]
Hi @waldekmastykarz,

This PR introduces new content that needs to be pulled into the private repo for staging, validation, and Acrolinx and to get it merged.

If you need it, the metadata/ownership info and the process for pulling content to the private repo is documented [here](https://review.docs.microsoft.com/help/contribute/contribute-how-to-manage-act-guidelines-public-pr?branch=main#pull-public-commits-to-the-private-repo-for-updates-staging-publication).

Leave a comment if you'd like the PR review team's help with moving these commits.

Thanks!

**Comment by Court72** [comment]
These changes have been merged in https://github.com/MicrosoftDocs/microsoft-cloud-pr/pull/232.

**Pull request closed without merging**
